import type { SayisalAlan } from "../../shared/utils/sayisalDogrulama";

export type MKUItkiKomutaPaket = {
  geriSayim_sn: SayisalAlan;
  anahtarKontrolu: SayisalAlan;
  seciliValf_0: SayisalAlan;
  seciliIslem_0: SayisalAlan;
  islemSuresi_0: SayisalAlan;
  seciliValf_1: SayisalAlan;
  seciliIslem_1: SayisalAlan;
  islemSuresi_1: SayisalAlan;
  seciliValf_2: SayisalAlan;
  seciliIslem_2: SayisalAlan;
  islemSuresi_2: SayisalAlan;
  seciliValf_3: SayisalAlan;
  seciliIslem_3: SayisalAlan;
  islemSuresi_3: SayisalAlan;
  seciliValf_4: SayisalAlan;
  seciliIslem_4: SayisalAlan;
  islemSuresi_4: SayisalAlan;
  seciliValf_5: SayisalAlan;
  seciliIslem_5: SayisalAlan;
  islemSuresi_5: SayisalAlan;
  seciliValf_6: SayisalAlan;
  seciliIslem_6: SayisalAlan;
  islemSuresi_6: SayisalAlan;
  seciliValf_7: SayisalAlan;
  seciliIslem_7: SayisalAlan;
  islemSuresi_7: SayisalAlan;
  seciliValf_8: SayisalAlan;
  seciliIslem_8: SayisalAlan;
  islemSuresi_8: SayisalAlan;
  seciliValf_9: SayisalAlan;
  seciliIslem_9: SayisalAlan;
  islemSuresi_9: SayisalAlan;
};
